// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtGBZa4izPCMSApxjriTeV3GS81xake9I',
    appId: '1:308631587519:web:c3af006eb8e03a6e31d40a',
    messagingSenderId: '308631587519',
    projectId: 'kavach-3a2f4',
    authDomain: 'kavach-3a2f4.firebaseapp.com',
    storageBucket: 'kavach-3a2f4.firebasestorage.app',
    measurementId: 'G-V8Q19EPHWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcQngwgm0qsxQLM6CdF2zGMf8KI3hkKts',
    appId: '1:308631587519:android:f27c6bcc5327c68d31d40a',
    messagingSenderId: '308631587519',
    projectId: 'kavach-3a2f4',
    storageBucket: 'kavach-3a2f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJRzmvw0llCfQMXcvHQ7Y1S3XYhthyF4',
    appId: '1:308631587519:ios:c00bce73ef8526d131d40a',
    messagingSenderId: '308631587519',
    projectId: 'kavach-3a2f4',
    storageBucket: 'kavach-3a2f4.firebasestorage.app',
    iosBundleId: 'com.example.kavach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlJRzmvw0llCfQMXcvHQ7Y1S3XYhthyF4',
    appId: '1:308631587519:ios:c00bce73ef8526d131d40a',
    messagingSenderId: '308631587519',
    projectId: 'kavach-3a2f4',
    storageBucket: 'kavach-3a2f4.firebasestorage.app',
    iosBundleId: 'com.example.kavach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtGBZa4izPCMSApxjriTeV3GS81xake9I',
    appId: '1:308631587519:web:b56996150f132a6431d40a',
    messagingSenderId: '308631587519',
    projectId: 'kavach-3a2f4',
    authDomain: 'kavach-3a2f4.firebaseapp.com',
    storageBucket: 'kavach-3a2f4.firebasestorage.app',
    measurementId: 'G-2PM9XBB16R',
  );
}
